# Generated by Django 4.2.2 on 2023-06-11 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductName',
        ),
    ]
