# Generated by Django 4.2.2 on 2023-06-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_product_name_product_p_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='name',
        ),
    ]
