# Generated by Django 4.2.2 on 2023-06-11 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_p_name_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Buy',
        ),
    ]
